// Assembles the ce-code-review dynamic workflow into a single self-contained
// script. The Workflow runtime cannot import sibling files and requires
// `export const meta` as the first statement, so the canonical, unit-tested
// merge module (merge-findings.js) is inlined into the fan-out template
// (code-review-fanout.js) at its merge-module marker.
//
// The mode:agent guard in SKILL.md reads the GENERATED output and passes it to
// the Workflow tool verbatim — no runtime text-surgery. Regenerate after
// editing either source:
//
//   bun run scripts/build-review-workflow.ts
//
// A freshness test (tests/review-workflow-parity.test.ts) fails if the
// committed generated file drifts from the sources.

import { readFile, writeFile } from "fs/promises"
import path from "path"

const WF_DIR = "plugins/compound-engineering/skills/ce-code-review/workflows"
const MARKER = "/* __MERGE_MODULE__ */"
export const GENERATED_PATH = `${WF_DIR}/code-review-fanout.generated.js`

const GENERATED_HEADER =
  "// GENERATED by scripts/build-review-workflow.ts — DO NOT EDIT.\n" +
  "// Edit code-review-fanout.js (fan-out) or merge-findings.js (merge), then run:\n" +
  "//   bun run scripts/build-review-workflow.ts\n\n"

/** Produce the assembled workflow script (with the generated header). */
export async function assembleReviewWorkflow(root: string = process.cwd()): Promise<string> {
  const merge = await readFile(path.join(root, `${WF_DIR}/merge-findings.js`), "utf8")
  const fanout = await readFile(path.join(root, `${WF_DIR}/code-review-fanout.js`), "utf8")

  // Drop the module's trailing `export { ... };` so the inlined source is valid
  // inside the export-less workflow script. Function replacement keeps `$` in
  // the inserted source (template literals) literal.
  const mergeInline = merge.replace(/\nexport\s*\{[^}]*\};\s*$/, "\n")
  if (mergeInline === merge) {
    throw new Error("merge-findings.js: expected a trailing `export { ... };` to strip")
  }
  if ((fanout.match(/\/\* __MERGE_MODULE__ \*\//g) || []).length !== 1) {
    throw new Error("code-review-fanout.js: merge-module marker must appear exactly once")
  }

  return GENERATED_HEADER + fanout.replace(MARKER, () => mergeInline)
}

if (import.meta.main) {
  const out = await assembleReviewWorkflow()
  await writeFile(path.join(process.cwd(), GENERATED_PATH), out, "utf8")
  console.log(`Wrote ${GENERATED_PATH} (${out.length} bytes)`)
}
