// Assembles the ce-compound-refresh dynamic workflow into a single self-contained
// script. The Workflow runtime cannot import sibling files and requires
// `export const meta` as the first statement, so the canonical, unit-tested
// deterministic module (classify-rollup.js) is inlined into the fan-out template
// (corpus-audit-fanout.js) at its merge-module marker.
//
// The guard in SKILL.md reads the GENERATED output and passes it to the Workflow
// tool verbatim — no runtime text-surgery. Regenerate after editing either
// source:
//
//   bun run scripts/build-compound-refresh-workflow.ts
//
// A freshness test (tests/compound-refresh-workflow-parity.test.ts) fails if the
// committed generated file drifts from the sources.

import { readFile, writeFile } from "fs/promises"
import path from "path"

const WF_DIR = "plugins/compound-engineering/skills/ce-compound-refresh/workflows"
const MARKER = "/* __MERGE_MODULE__ */"
export const GENERATED_PATH = `${WF_DIR}/corpus-audit-fanout.generated.js`

const GENERATED_HEADER =
  "// GENERATED by scripts/build-compound-refresh-workflow.ts — DO NOT EDIT.\n" +
  "// Edit corpus-audit-fanout.js (fan-out + contradiction loop) or classify-rollup.js (normalize + roll-up), then run:\n" +
  "//   bun run scripts/build-compound-refresh-workflow.ts\n\n"

/** Produce the assembled workflow script (with the generated header). */
export async function assembleCorpusAuditWorkflow(root: string = process.cwd()): Promise<string> {
  const moduleSrc = await readFile(path.join(root, `${WF_DIR}/classify-rollup.js`), "utf8")
  const fanout = await readFile(path.join(root, `${WF_DIR}/corpus-audit-fanout.js`), "utf8")

  // Drop the module's trailing `export { ... };` so the inlined source is valid
  // inside the export-less workflow script. Function replacement keeps `$` in
  // the inserted source (template literals) literal.
  const moduleInline = moduleSrc.replace(/\nexport\s*\{[^}]*\};\s*$/, "\n")
  if (moduleInline === moduleSrc) {
    throw new Error("classify-rollup.js: expected a trailing `export { ... };` to strip")
  }
  if ((fanout.match(/\/\* __MERGE_MODULE__ \*\//g) || []).length !== 1) {
    throw new Error("corpus-audit-fanout.js: merge-module marker must appear exactly once")
  }

  return GENERATED_HEADER + fanout.replace(MARKER, () => moduleInline)
}

if (import.meta.main) {
  const out = await assembleCorpusAuditWorkflow()
  await writeFile(path.join(process.cwd(), GENERATED_PATH), out, "utf8")
  console.log(`Wrote ${GENERATED_PATH} (${out.length} bytes)`)
}
